const {chromium}=require('playwright');const fs=require('fs');const {PNG}=require('pngjs');
(async()=>{const root=__dirname, manifest=JSON.parse(fs.readFileSync(root+'/manifest.json','utf8'));fs.mkdirSync(root+'/review',{recursive:true});const b=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH}:{})});const views=[];
for(const viewport of [{width:390,height:844},{width:360,height:800}]){const p=await b.newPage({viewport,deviceScaleFactor:1});await p.goto('file://'+root+'/reader.html');await p.waitForLoadState('load');const d=await p.evaluate(()=>{const figs=[...document.querySelectorAll('figure.scene')];return{width:innerWidth,viewportHeight:innerHeight,pageWidth:document.documentElement.scrollWidth,pageHeight:document.documentElement.scrollHeight,images:[...document.images].map(i=>({loaded:i.complete&&i.naturalWidth>0,src:i.getAttribute('src').slice(0,35),naturalWidth:i.naturalWidth,naturalHeight:i.naturalHeight,displayWidth:i.getBoundingClientRect().width})),order:figs.map(e=>({id:e.id,top:e.getBoundingClientRect().top,height:e.getBoundingClientRect().height})),htmlDialogueCount:document.querySelectorAll('.dialogue,.thought,.system').length,pending:document.querySelectorAll('.pending').length}});
if(d.width!==viewport.width||d.pageWidth>d.width||d.pending||d.images.length!==manifest.shots.length||d.images.some(i=>!i.loaded)||d.htmlDialogueCount||d.order.map(o=>o.id).join(',')!==manifest.shots.map(s=>s.id).join(','))throw new Error(JSON.stringify(d));
d.coreToHero=d.order.find(o=>o.id==='hero').top-d.order.find(o=>o.id==='core').top;d.coreBottomToHero=d.order.find(o=>o.id==='hero').top-(d.order.find(o=>o.id==='core').top+d.order.find(o=>o.id==='core').height);d.measurementWaitDistance=(d.order.find(o=>o.id==='result').top+d.order.find(o=>o.id==='result').height*0.64)-(d.order.find(o=>o.id==='waiting').top+d.order.find(o=>o.id==='waiting').height*0.75);if(d.measurementWaitDistance<viewport.height)throw Error('Wait cue and first zero result are visible together');d.measurementFlow=d.order.filter(o=>['instruction','hesitation','touch','waiting','result','confirmation','stakes','rejection','zero_reaction'].includes(o.id));d.touchToResult=d.order.find(o=>o.id==='result').top-d.order.find(o=>o.id==='touch').top;d.arrivalToMeasurement=d.order.find(o=>o.id==='touch').top-d.order.find(o=>o.id==='waking').top;d.fallToCatch=d.order.find(o=>o.id==='catch').top-d.order.find(o=>o.id==='fall').top;
if(d.coreToHero<viewport.height||d.fallToCatch<viewport.height)throw Error('Reveal or falling action is compressed below the viewport height');

for(const s of manifest.shots)await p.locator('#'+s.id).screenshot({path:root+'/review/scene-'+viewport.width+'-'+s.id+'.png'});
const full=new PNG({width:viewport.width,height:d.pageHeight});let tiles=0;for(let y=0;y<d.pageHeight;y+=viewport.height){const actualTop=await p.evaluate(y=>{scrollTo(0,y);return scrollY},y);const raw=await p.screenshot({path:root+'/review/screen-'+viewport.width+'-'+Math.floor(y/viewport.height)+'.png'});const shot=PNG.sync.read(raw);if(shot.width!==viewport.width||shot.height!==viewport.height)throw Error('Screenshot dimensions do not match CSS viewport');const offset=y-actualTop,count=Math.min(viewport.height,d.pageHeight-y),stride=shot.width*4;if(offset<0||offset+count>shot.height)throw Error('Invalid scroll tile overlap');for(let row=0;row<count;row++)shot.data.copy(full.data,(y+row)*stride,(offset+row)*stride,(offset+row+1)*stride);tiles++;}fs.writeFileSync(root+'/complete-'+viewport.width+'.png',PNG.sync.write(full));d.rasterExport={method:'viewport screenshots joined without modifying any source artwork',tiles,width:viewport.width,height:d.pageHeight};views.push(d);await p.close();}
await b.close();fs.writeFileSync(root+'/validation.json',JSON.stringify({version:'v5',viewports:views,generation:'16 new shots expand approach and measurement; 14 accepted v4 artworks preserved. New dialogue generated with built-in image_gen inside raster art.',lettering:'True vertical Japanese. Raster glyphs are checked visually; DOM font metrics do not measure their size.',visualReview:'pending'},null,2));console.log(JSON.stringify(views.map(v=>({width:v.width,height:v.pageHeight,images:v.images.length,pageWidth:v.pageWidth,htmlDialogueCount:v.htmlDialogueCount,coreToHero:v.coreToHero,coreBottomToHero:v.coreBottomToHero,fallToCatch:v.fallToCatch,measurementWaitDistance:v.measurementWaitDistance,touchToResult:v.touchToResult,arrivalToMeasurement:v.arrivalToMeasurement}))));})();
