"""Original story bible and scene scripts for chapters 2–10.

Artwork is generated separately. This file contains no generated-image substitutes.
"""

CHARACTERS = {
    "阿澄": "17歳。黒髪を低く結ぶ。琥珀色の瞳。左こめかみに白い包帯。生成りの稽古衣、青灰の襟と帯。胸に傷はない。前世は白髪の剣聖・凌雪。木剣一本。",
    "沈玄": "40代。高い黒髪の結び、口髭と短い顎髭。墨緑の衣、黒い羽毛肩衣、真鍮の留め具。腰に鞘入りの剣一本。第9話までは無傷。第9話末に左前腕を負傷。",
    "葉青": "19歳の先輩門弟。長い黒髪を一本の三つ編みにし、翡翠の髪留め。淡い青緑の衣、白い襟、濃緑の帯。薬草と炊事を担当。阿澄を以前から知る。恋愛の説明はしない。",
}

def scene(name, mode, art, lines, purpose):
    return {"name": name, "mode": mode, "art": art, "lines": lines, "purpose": purpose}

CHAPTERS = [
    {"number": 2, "title": "掴めない手", "change": "助けを受け取れない阿澄が、差し出された手の代わりに師匠の袖を掴む。復讐はまだ行動にできない。", "scenes": [
        scene("引いた指", "panels", "Five sequential moments: the master's open uninjured palm; the boy's fingers stopping a finger-width away; his fingers retracting; his amber eyes avoiding the master's eyes; the master's palm quietly lowering. Snowy courtyard, wooden sword on the ground, nobody shakes hands.", ["T|弟子。\n俺が、こいつの。", "T|この手で、俺は殺された。", "S阿澄|……大丈夫です。", "S沈玄|そうか。", "T|手が下りた。\n追っては来なかった。"], "前話の手のためらいを受ける。拒否後の静けさ。"),
        scene("戻る足音", "route", "One continuous vertical composition. Top: master's boots turn away in snow. Middle: a single trail of fresh footprints leads down the courtyard stones. Bottom: the boy alone attempts to push himself upright by a stone water basin. The master is offscreen at the bottom, no face reveal.", ["S沈玄|立てるなら、戻るぞ。", "T|背を向けた。\n今なら、逃げられる。", "T|……足が、動かない。"], "足跡をたどり、自分の身体の遅さに戻る。"),
        scene("膝の重さ", "panels", "Five unequal sequential close shots: boy's palm braced on damp stone; one knee lifting; his leg visibly trembling; his eyes widening as balance fails; a full figure slumping back to kneel safely. No bloody injury. Sword remains on the ground.", ["T|頭では立っている。", "T|身体が、一息遅れる。", "S阿澄|っ……。", "T|こんな膝で、\nあいつに勝てるのか。", "T|答えは、立つより先に出た。"], "失敗を細かく、沈黙は失敗の後へ置く。"),
        scene("木剣の行き先", "panels", "Five successive close views: wooden sword in snow; master's dark sleeve entering; his hand picking up the one wooden sword by the grip; snowy drops falling from its tip; his hand holding the sword at his side, safely pointed down. Boy looks up in the final view.", ["N|足音が、戻ってきた。", "T|木剣を、拾うのか。", "S沈玄|無理に立つな。", "S阿澄|……それは、俺の。", "S沈玄|分かっている。"], "剣の所有を保ち、奪ったのかと思わせて返す。"),
        scene("袖をつかむ", "panels", "Five sequential actions: master crouches at respectful distance while holding the wooden sword in his left hand; his right arm offers a sleeve-covered forearm instead of bare palm; boy watches the sleeve; boy cautiously grips only the fabric with one hand; boy pulls himself up using the sleeve, master braces him without a handshake. Correct two hands per person.", ["S沈玄|手が嫌なら、袖でいい。", "T|嫌だと、言っていない。", "T|布なら。\nあの手を見なくて済む。", "S阿澄|……少しだけ。", "T|握ったのは、\n仇の手ではなかった。"], "接触の選択を描き、握手成立と誤読させない。"),
        scene("叱らない顔", "hero", "A tall borderless close portrait of Shen Xuan, same dark green robe and black feather mantle, looking down with a restrained tired expression rather than a smile. His right sleeve has one small boy's hand gripping the fabric near the cuff, bottom only. Snow dissolves into white paper.", ["T|叱られると思った。", "S沈玄|今日の稽古は、終わりだ。", "T|あいつは、\n何も聞かなかった。"], "待っていた叱責の代わりに静かな顔。"),
        scene("二人分の跡", "panels", "Five consecutive moments: two pairs of feet walking slowly with the master matching the boy's pace; boy's hand still on dark sleeve; boy glancing at the master's sheathed sword; two figures approaching a wooden covered corridor; a plain ceramic bowl with rising steam glimpsed through a doorway. The master carries the single wooden sword, boy empty handed.", ["T|刃を抜けば、\n届く距離にいる。", "T|なのに今は、\n袖を離すこともできない。", "S沈玄|飯を食え。話は、そのあとだ。", "N|戸の向こうから、\n米の匂いがした。", "T|生きている身体は、\n腹が減るらしい。"], "袖と足音で室内へ。次話の粥を最後だけ見せる。"),
    ]},
    {"number": 3, "title": "一椀の粥", "change": "敵が毒を盛ると思った阿澄が、葉青の粥を食べる。少年自身の過去に空白があると知る。", "scenes": [
        scene("湯気の向こう", "panels", "Five sequential intimate kitchen shots: steam from a plain ceramic bowl of rice porridge; bowl set on wood by a woman's hands with pale jade sleeves; boy watches bowl suspiciously; chopsticks untouched beside bowl; boy's stomach reacts and his lips press together. Do not show woman's face yet.", ["N|温かい匂い。", "T|毒なら、\n匂いでは分からない。", "S葉青|冷めるよ、阿澄。", "T|腹が鳴った。\n身体まで、敵に味方する。", "S阿澄|……誰だ。"], "声と手を先に、新人物の顔は次の下へ。"),
        scene("炊事場の朝", "route", "One continuous downward kitchen composition: roof beams and soft winter daylight at top; a hanging ladle and steam curl leading downward; at bottom a 19-year-old young woman with one black braid, jade hairpin, pale jade robe and dark green belt, standing by the stove looking toward the seated boy. Snow visible through the window. No text.", ["S葉青|葉青。昨日も粥、持ってきた。", "T|昨日。\n俺の知らない、昨日だ。", "S葉青|頭、まだ痛む？"], "湯気を下へたどって葉青を初めて見せる。"),
        scene("忘れたふり", "panels", "Five successive close shots: boy's fingertips approach his left-temple white bandage; woman stops her stirring spoon midair; boy looks down, avoiding questions; woman gently resumes stirring; the master's empty seat beside the door, wooden sword leaning safely against it. Master offscreen.", ["S阿澄|……少し。", "T|この少年の記憶は、\n一つもない。", "S葉青|転んだ時のこと、\n無理に思い出さなくていい。", "T|転んだ？\n誰かと戦ったのではなく。", "S阿澄|師匠は、どこに。"], "転生の全説明をせず、身体の前歴を会話へ。"),
        scene("確かめる箸", "panels", "Five close consecutive food actions: boy picks up wooden chopsticks; lifts a small clump of plain rice porridge; stops it before his lips; woman's own bowl and spoon taking an ordinary bite; boy watches her swallow. No poisonous vapor or magical effect, ordinary food.", ["S葉青|山門。\n朝の見回り。", "T|自分では食べず、\n他人に食わせるのか。", "S葉青|……そんなに見られると、\n食べにくいんだけど。", "S阿澄|毒味、じゃない。", "S葉青|そういう顔だったよ。"], "小さな疑いと軽い応答。恋愛や強制給餌はない。"),
        scene("ひと口", "panels", "Five sequential food and emotion shots: boy takes one small bite himself; steam rises around his lowered eyes; his tense brow softens involuntarily; his left hand steadies bowl; a drop of condensation runs down the bowl onto the table. No crying, no smile forced, restrained sensory relief.", ["T|熱い。", "T|喉を通るまで、\n味を忘れていた。", "S葉青|……食べられて、よかった。", "T|毒の味ではない。\n米と、水と、少しの塩。", "T|こんなものに、\n気が緩むなんて。"], "食べる一動作を感覚へ分け、滴で余韻へ。"),
        scene("欠けた器", "hero", "Tall borderless still life at human scale: boy's hands around a plain white-grey ceramic bowl with one small old chip on its rim. Warm porridge inside, visible chopsticks beside it, pale jade sleeve on the other side of the table. Quiet white background and soft winter light. No written markings.", ["S葉青|それ、前からあんたの器。", "T|俺ではない誰かが、\nここで生きていた。", "T|この欠けた場所まで、\n覚えていたんだろうか。"], "欠けた器を、少年の生活の証拠にする。"),
        scene("小さな約束", "panels", "Five sequential quiet shots: empty porridge bowl set down; woman folding a clean cloth; boy listening as she indicates the window; snowy path toward herb shed outside; boy watches his hands, then carefully folds the cloth once. Master absent, no action attack.", ["S葉青|午後、薬草運び。\n無理なら、見てるだけでいい。", "S阿澄|……運ぶ。", "T|門の中を見ておきたい。\nそれだけだ。", "S葉青|じゃあ、ゆっくりね。", "N|何をしていいか分からない朝に、\n一つだけ、することができた。"], "小さな生活の約束で次の回へ。"),
    ]},
    {"number": 4, "title": "息をほどく", "change": "昔の剣技は弱い身体に合わない。師匠の呼吸指導から、一つだけ動きが戻る。", "scenes": [
        scene("重い束", "panels", "Five consecutive shots: herb bundles tied with string on a wooden shelf; boy lifting one small bundle; herbs nearly slip from his shaking fingers; pale jade-sleeved Ye Qing takes the heavy basket herself; boy keeps only the small light bundle. Same winter robes, bandage.", ["N|薬草は、\n木剣より軽い。", "T|それすら、落としかけた。", "S葉青|力むと、余計に震えるよ。", "S阿澄|分かってる。", "T|分かっていて、\nできない。"], "筋力の問題を、前話の約束に続けて見せる。"),
        scene("軒下の呼吸", "route", "A single continuous vertical winter courtyard view: thin herb stems hanging to dry at top, wind carries one loose leaf down through a long quiet white middle, at bottom the boy seated under wooden eaves looking at his chest while the master stands at a distance. No sword drawing or magical aura.", ["S沈玄|息を止めるな。", "T|呼吸まで、\nこいつに言われるのか。", "N|乾いた葉が、\n一枚、下りてきた。"], "葉の落下が呼吸を見直す時間をつくる。"),
        scene("古い型", "panels", "Five consecutive training shots: boy with single wooden sword lifts tip into an expert old stance; shoulders tighten; hands squeeze grip too hard; feet misalign while trying to step; boy safely stops sword before striking. Master watches without approaching, no glow and no superpower success.", ["T|型は、忘れていない。", "T|二十九年、繰り返した動きだ。", "S沈玄|肩。", "S阿澄|……何が。", "S沈玄|先に、そこを下ろせ。"], "前世の達人と身体の失敗。力の覚醒を急がない。"),
        scene("ほどく指", "panels", "Five sequential close shots: master's open palm demonstrates relaxed fingers, not touching boy; boy loosens index finger from wooden grip; his forearm gradually eases; his shoulders lower; his held breath leaves as visible winter condensation. Hands anatomically correct and grip stays on one sword.", ["T|握りを緩めれば、\n剣を落とす。", "S沈玄|落としても、ここには敵がいない。", "T|いる。目の前に。", "S沈玄|吐いてから、吸え。", "N|白い息が、\nようやく、外へ出た。"], "視覚的に手から息までつなぎ、触らず教える。"),
        scene("半歩だけ", "panels", "Five restrained consecutive training moments: boy places one foot forward half a step; wooden sword tip moves a small controlled distance; a loose leaf brushes the blade harmlessly; boy's eyes register a tiny success; feet stop steady, no dramatic attack. Master remains watching at edge.", ["T|半歩。", "T|斬るには、\nあまりに短い。", "S沈玄|今は、それでいい。", "T|けれど、初めて、\n身体が遅れなかった。", "S阿澄|……もう一度。"], "小さな前進を成功として止まり、チート化しない。"),
        scene("何かを知る目", "hero", "Tall intimate close portrait of Shen Xuan's eyes and face, restrained recognition and sadness hidden under a composed expression. Black hair in high tie, beard, black feather mantle. One fallen herb leaf in the soft white foreground. No flashback, no weapon in hand.", ["T|褒めた顔では、なかった。", "S沈玄|今日は、ここまで。", "T|俺の型を、\nどこで見た？"], "成功の後に師匠の認識を一瞬だけ置く。"),
        scene("呼吸を残す", "panels", "Five closing moments: wooden sword set beside boy's knee; boy sits under eaves, breathing slowly; master walks away through courtyard with sheathed sword; boy's fingertips mimic the old grip against empty palm; leaf lands gently in the palm. Winter remains, no blood.", ["S阿澄|まだ、できます。", "S沈玄|できる日に、\nできる分だけやれ。", "T|こんな教え方を、\n剣聖は知らなかった。", "T|誰にも、教わらなかった。", "N|掌に落ちた葉が、\nさっきより、軽かった。"], "呼吸と葉の小さな変化で終える。"),
    ]},
    {"number": 5, "title": "石段の下", "change": "門の中を探る阿澄が足を滑らせる。仇が庇う手の記憶と、前世の最期の記憶が食い違う。", "scenes": [
        scene("知らない道", "panels", "Five successive shots: boy ties blue-grey belt securely; picks up a small empty herb basket; looks through wooden corridor; hears distant bell, still offscreen; his feet turn toward a descending stone stair. Bandage still left temple, no wooden sword carried.", ["N|翌朝。", "T|この門を、\n一人で歩いてみる。", "T|あいつの部屋。出口。\n誰が、どこにいるのか。", "N|遠くで、鐘が鳴った。", "T|山門は、下か。"], "調査の目的を小さく。外の大事件へは進めない。"),
        scene("長い石段", "route", "One continuous very tall composition down a snowy mountain monastery stone stair, with top boy seen from behind beginning descent with empty herb basket, long middle steps and snow melt stream guiding eye, bottom only distant wooden gate partly hidden in mist. No accident or savior visible yet.", ["T|一段。\nもう、一段。", "T|こんな階段を、\n昔は息もせず下りた。", "N|雪の下に、\n水が流れていた。"], "石段で身体の時間と距離を感じさせる。"),
        scene("滑る音", "panels", "Five sequential accident cues: shoe touches thin ice on stair; ice glints; shoe sole slips a small distance; boy's hand reaches for railing; light empty herb basket tilts with no herbs falling. No drop off cliff and no exaggerated deadly fall.", ["T|濡れている。", "N|気づいた時には、", "S阿澄|っ。", "T|手すりが、遠い。", "T|足が、ついてこない。"], "短い動作を密にして速度を変える。"),
        scene("止まった落下", "panels", "Five consecutive rescue details: dark green sleeve enters; master's strong uninjured hand catches boy by upper arm through sleeve; boy's other hand grips railing; boy's shoes settle securely on same stair; herb basket lands safely on adjacent step. Correct two arms each; master carries no drawn blade.", ["N|袖が、視界に入った。", "S沈玄|動くな。", "T|掴まれた。", "T|あの夜も、\nこいつは俺の腕を掴んだ。", "S沈玄|足を、ここへ。"], "助ける手を接写し、記憶との違いを作る。"),
        scene("記憶のずれ", "panels", "Five restrained shots alternating present only: boy stares at master's hand holding his sleeve; boy's chest under intact cream clothing; master's sheathed sword at waist; boy's amber eye wide; grip loosens once boy is stable. Do not illustrate new explicit stabbing flashback or show wounds.", ["T|斬る前に、腕を掴んだ。", "T|逃がさないためだと、\nずっと思っていた。", "S沈玄|どこか、痛めたか。", "S阿澄|……いえ。", "T|今の手は、\n落ちる俺を止めた。"], "前世の情報を更新するが、犯人の答えは出さない。"),
        scene("近すぎる仇", "hero", "Tall close portrait of master and boy at different heights on stone stairs. Master's concerned eyes looking at the boy's forehead bandage; boy avoids his gaze, tense and confused. Dark green robe, black feathers, snow. Master holds no blade and his arms uninjured.", ["S沈玄|一人で来るには、\nまだ早い。", "T|怒る声より先に、\n手が来た。", "T|なぜ、助ける。"], "答えをもらえない近い顔。救助と信頼を同義にしない。"),
        scene("一段戻る", "panels", "Five final moments: master picks up the empty herb basket; boy steps upward holding railing independently; master follows one step behind, not pulling him; boy looks back once at the long stairs; footprints now head upward. No hand clasp, no hug.", ["S阿澄|……自分で、上がれます。", "S沈玄|では、一段ずつ。", "T|背中に、足音がある。", "T|離れない。\n急がせもしない。", "N|この男を殺す理由は、\nまだ、一つも減っていない。\n疑問だけが、増えた。"], "上へ戻る動きで、復讐と疑問が併存する結末。"),
    ]},
    {"number": 6, "title": "門の外の風", "change": "門外からの薬の荷を受け取り、三日前に阿澄も外で見つかったと聞く。送り主の印が前世とつながる。", "scenes": [
        scene("二人で運ぶ", "panels", "Five successive shots: Ye Qing ties cloth round empty herb basket; boy watches from door; she places only a small parcel in his hands; boy checks weight and balances it; both turn toward lower covered gate corridor. Bandaged boy now walks steadily but slowly.", ["S葉青|今日は、二人で。", "S阿澄|監視か。", "S葉青|荷物持ち。\nあたし一人じゃ、手が足りない。", "T|軽い包みだけ、渡された。", "T|気を遣われるのは、\nまだ慣れない。"], "前話の事故を受けて外出の条件を変える。"),
        scene("門が開く", "route", "One continuous vertical gate composition: heavy wooden gate lintel with melting snow at top; hanging unlettered bell and rope lead down; middle tall partially opened gate with bright white mountain mist; bottom boy and jade-robed woman stepping only onto the threshold, not into the valley. Wind lifts sleeves.", ["N|木が、軋んだ。", "T|門の外。", "T|知らない山なのに、\n風だけは、同じ匂いがした。"], "開く門と風で外の世界を一度だけ見せる。"),
        scene("小さな荷", "panels", "Five consecutive object-focused shots: a stack of plain medicine parcels at gate with no courier; woman's braid in wind; her hands sort plain cloth packets; boy reaches for one small packet; parcel cord snags lightly on his sleeve. No written labels or characters on parcels.", ["S阿澄|誰が、持ってきた。", "S葉青|麓の薬師。\n夜明け前に置いていくの。", "T|人の顔は、見えない。", "S葉青|山にいると、\n外はいつも、少し遅れて届く。", "N|紐が、袖に引っかかった。"], "外の人物を増やさず物で情報を運ぶ。"),
        scene("前にもここで", "panels", "Five quiet successive shots: boy loosens parcel cord from his cuff; woman's expression becomes thoughtful; she looks at the outer threshold stones; boy's bandage and startled amber eyes; a empty patch of damp stone just outside gate. No body lying there now, no new flashback.", ["S葉青|あんたも、そこにいた。", "S阿澄|……いつ。", "S葉青|三日前。\n師匠が、抱えて戻ってきた。", "T|転んだ場所は、\n稽古場ではなかった。", "S阿澄|俺は、外に出たのか。"], "少年の事故の場所を更新。全記憶はまだ戻さない。"),
        scene("知らない昨日", "panels", "Five moments: woman's palm rests on basket handle; she shakes head slightly; boy examines his own uninjured wrists; shadow of closed gate falls over stone; boy lowers his eyes, holding parcel. Nothing supernatural visually.", ["S葉青|出たところは、誰も見てない。", "S葉青|だから、聞かなくていいって、\n師匠が。", "T|誰にも見られずに、\n外へ出た少年。", "T|その身体に、\n俺がいる。", "T|偶然だと、\n思っていいのか。"], "事情を聞けないことが疑いを増やす。"),
        scene("結び目の印", "hero", "Tall macro close-up of one small bronze seal attached to parcel cord, engraved with an abstract split-circle-and-three-rays emblem (no readable text). Boy's slender fingertips hold cord carefully. Cream sleeve, snow and gate wood faded in background. Emblem clearly focal and large.", ["T|この印。", "T|凌雪の葬儀に、\n来るはずだった連中の。", "N|思い出したのは、\n名ではなく、形だった。"], "小道具の正体は大きく下で見せる。文字生成不要。"),
        scene("しまった紐", "panels", "Five concluding close shots: boy rotates small bronze emblem; woman's gaze stays on herb parcels, unaware; boy slips loosened small cord with seal into sleeve without taking medicine; gate quietly closes; master silhouette seen far across courtyard, boy watches from threshold. No confrontation.", ["S葉青|その紐、切れてる？", "S阿澄|……結び直しておく。", "T|薬の包みは、返した。", "T|印だけ、袖に残った。", "N|この山の外で、\n誰かが、今も、\n剣聖の死を知っている。"], "手掛かりを一つだけ持ち帰り次話へ。"),
    ]},
    {"number": 7, "title": "斬らない剣", "change": "昔の剣筋を隠して稽古するが師匠に気づかれる。殺す以外の剣の使い方を初めて学ぶ。", "scenes": [
        scene("袖の秘密", "panels", "Five sequential details: bronze emblem hidden wrapped inside boy's sleeve; he fastens cuff; picks up wooden sword; glances toward master at courtyard; sets his feet into deliberately ordinary novice stance. Master uninjured, sword sheathed.", ["T|印を見せれば、\n何か話すだろうか。", "T|先に、俺の方が疑われる。", "S沈玄|今日は、受ける稽古だ。", "S阿澄|斬るのではなく？", "S沈玄|そうだ。"], "袖の秘密を保ちつつ一つの稽古へ。"),
        scene("枝の軌道", "route", "One continuous vertical teaching composition: slender bare willow branch held by master's hand at top; gentle descending arc through airy white space; lower middle boy tracks it with eyes; bottom branch points toward a fallen leaf at boy's feet without contact. No magic energy, no attack on body.", ["S沈玄|この枝を、外せ。", "T|細い枝一本。\n相手にするには、軽すぎる。", "N|先端が、ゆっくり、下りてきた。"], "軌道をたどって受ける対象を読ませる。"),
        scene("切る癖", "panels", "Five sequential training moments: branch approaches safely at chest level; boy's eyes sharpen; wooden sword reflexively lifts into aggressive expert cut; master stops branch before contact; boy freezes, realizing old stance shown. No blade, no bodily strike, no splintering.", ["T|隙がある。", "T|斬れば、終わる。", "S沈玄|止めろ。", "S阿澄|……当てていない。", "S沈玄|今のは、受ける剣ではない。"], "短い身体反射で正体が漏れかける。"),
        scene("覚えている身体", "panels", "Five close successive shots: boy loosens jaw; his hand hides grip slightly under sleeve; master's eyes study sword angle; boy changes stance to clumsy novice; master lowers branch, giving distance. Bronze seal remains invisible under cuff.", ["T|この身体は、\n何も覚えていないはずだ。", "T|覚えているのは、俺だ。", "S沈玄|誰に、その型を教わった。", "S阿澄|……夢で。", "N|枝の先が、止まった。"], "嘘に対する返事の前に長い間。"),
        scene("外へ逃がす", "panels", "Five sequential clear defensive actions: master demonstrates branch with an open free palm; boy tilts flat side of one wooden sword slightly; branch slides sideways along wooden blade; boy's feet stay balanced rather than advance; branch tip harmlessly moves past his shoulder with visible separation. Correct non-cutting technique, no injuries.", ["S沈玄|なら、起きている間に、\n別の使い方を覚えろ。", "T|押し返さない。", "S沈玄|ぶつけず、\n外へ逃がせ。", "T|斬らなくても、\n前へ通さなければいい。", "S阿澄|……もう一度。"], "新しい剣を動作で見せる。受けが今後の救助に接続。"),
        scene("斬るだけの人", "hero", "Tall close portrait of boy in cream training robes, amber eyes resting on the flat of the wooden blade he holds upright at safe distance. Pensive not triumphant, left temple bandage, snowy pale background. No golden effects or power-up aura.", ["T|剣聖の剣は、\n斬るためにしか、なかった。", "T|この男の剣は、\n何のためにある。", "S沈玄|明日は、\n連れていく場所がある。"], "主人公の価値観を少し揺らし次話の行先を伏せる。"),
        scene("刃先を下ろす", "panels", "Five final actions: boy lowers wooden sword tip; master puts bare branch aside; boy practices one small deflection alone; fallen leaf passes unharmed beside sword; boy looks toward the distant mountain trees while holding blade down. No battle, seal still hidden.", ["S阿澄|……どこへ。", "S沈玄|歩ける分だけ、山の上へ。", "T|話を避けたのか。\n答えを見せるつもりか。", "N|剣先の前を、\n葉が一枚、通り過ぎた。", "T|斬らなかった。\nそれだけのことが、難しかった。"], "葉を斬らず通す動きで一話の練習を閉じる。"),
    ]},
    {"number": 8, "title": "名のない墓", "change": "師匠が通う山上の墓を見る。死者の名は削られ、師匠の黙祷だけが手掛かりとして残る。", "scenes": [
        scene("歩ける分だけ", "panels", "Five sequential departure shots: boy adjusts bandaged forehead gently; Ye Qing passes him a plain water flask; master waits at path entrance; boy chooses not to carry wooden sword; two sets of boots begin climb into white snowy forest. Boy carries water flask, seal under cuff.", ["S葉青|飲み水。\n今度は、一人で下りないで。", "S阿澄|分かってる。", "T|剣を、持たずに行く。", "T|持てば、\n抜く理由を探してしまう。", "S沈玄|ゆっくりでいい。"], "剣の不在を明示し、小道具の状態を固定。"),
        scene("山道の間", "route", "One continuous tall upward mountain path seen as downward reading route: at top two figures small among pine boughs; middle long footpath and falling powder snow leading eye; bottom bare old stone lantern and quiet clearing, no grave marker yet visible. Master always one step ahead, boy following with flask.", ["N|木の間に、\n風の音しかなかった。", "T|質問を、一つずつ、\n飲み込んで歩いた。", "T|言い出せば、\n仇だと叫んでしまいそうで。"], "山道を読む時間を質問を飲み込む時間にする。"),
        scene("休む背中", "panels", "Five consecutive rest moments: boy's feet slow; he stops to drink from water flask; master notices without turning fully; master pauses by pine trunk; boy caps flask and resumes step. No carrying or heroic collapse, independent effort.", ["T|息が、先に上がる。", "S沈玄|ここで、休む。", "S阿澄|まだ、歩けます。", "S沈玄|俺が、休みたい。", "T|嘘が、下手な男だ。"], "師匠の気遣いを言い切らず、息の間で描く。"),
        scene("置かれた花", "panels", "Five slowly revealing object shots: master's hand removes a small plain white flower from sleeve; snow brushed from a low stone; flower laid horizontally; boy's eyes follow; lower edge of a plain worn upright grave stone starts to enter final view but no full marker yet. No engraved text.", ["T|花を、持っていたのか。", "N|雪を払う手は、\n慣れていた。", "S阿澄|……誰の。", "N|返事はなかった。", "T|花を置く場所だけが、\n先に見えた。"], "花と手を先に置き墓を下へ隠す。"),
        scene("消えた文字", "panels", "Five sequential grave details: boy kneels at respectful distance; fingers hover above scraped patch on weathered grave stone without touching; coarse scraping marks on face with no legible letters; white flower at foot; master stands still behind boy. Grave is small plain gray stone, no human body.", ["T|名が、削られている。", "T|風に消えた傷ではない。\n誰かが、消した。", "S阿澄|どうして、名前がない。", "S沈玄|ここでは、\nそれでいい。", "T|ここでは。\n外では、違うのか。"], "墓の名前は生成文字にせず傷として描く。"),
        scene("黙祷", "hero", "Tall borderless full figure of Shen Xuan standing before the small anonymous grave, head bowed, eyes closed, uninjured hands at sides, sword fully sheathed. Boy partly at lower edge observing. White snow and pale pine boughs, one white flower. Solemn restrained grief, no dramatic tears.", ["N|あいつが、目を閉じた。", "T|俺を殺した男が、\n誰かのために、祈っている。", "T|この墓の前で、\n復讐のことだけ、考えられなかった。"], "墓の正体を明かす代わりに仇の哀悼へ止まる。"),
        scene("呼ばれない名", "panels", "Five closing moments: boy opens mouth to ask, then closes; master's eyes open; snow touches white flower; boy and master turn back toward path; behind them grave remains with scraped nameless surface, nobody present. Boy retains flask, no new token taken.", ["S阿澄|……また、来るんですか。", "S沈玄|来られる日は。", "T|毎日、とは言わなかった。", "N|帰り道は、\n行きより少し、短かった。", "T|墓の名は、知らない。\nけれど、忘れられてはいない。"], "謎を保持して日常の継続へ。次回で襲撃開始。"),
    ]},
    {"number": 9, "title": "雨の針", "change": "夜、雨音の中で針が飛ぶ。阿澄は習った受けを使うが身体が遅れ、師匠が左腕で庇う。", "scenes": [
        scene("雨になる夜", "panels", "Five sequential quiet indoor-evening details with white paper surrounding art: thawed snow dripping from eaves; boy places bronze emblem on wood table; boy studies abstract split-circle-and-three-rays seal; a small candle flame leans in wind; boy turns toward open corridor with wooden sword leaning nearby. No enemy yet.", ["N|雪は、夜に、雨になった。", "T|墓の名。\nこの印。", "T|どちらも、\n口に出せなかった。", "N|灯りが、ひとつ、揺れた。", "T|戸は、閉めたはずだ。"], "静かな夜の具体物から異変へ。白背景は維持。"),
        scene("雨をたどる", "route", "One continuous very tall rainy wooden corridor composition: top roof eaves with rain drip; middle long dark ink-green reflections in corridor floor fading into white paper, lantern light, no people or attackers; bottom empty threshold with one narrow glint of wet metal on wood only, no source shown. Smartphone vertical movement, not dark full-bleed background.", ["N|雨音に、\n別の音が混じった。", "T|一つだけ、硬い。", "N|ちん。"], "音から金属へ長くスクロールさせる。"),
        scene("一寸の針", "panels", "Five sequential close threat details: small slim metal dart embedded in wooden threshold; boy's amber eye notices; he retrieves single wooden sword safely; shifts one foot back; distant masked figure's lower boot just entering corridor at far end. No faces, no wound yet, no excessive dart quantity.", ["T|針。\n雨が落とすものではない。", "T|どこから。", "N|足音は、\n雨の方から来た。", "T|一人。\nいや、見えないところに、もう一人。", "S阿澄|師匠——。"], "正体全景はまだ出さず距離と数を音で示す。"),
        scene("声を出す前に", "panels", "Five fast sequential defensive action shots: second single metal dart flies from offscreen at a safe readable trajectory; boy raises flat of wooden sword; his wrist shakes; dart skims past flat, deflected slightly but not stopped; boy's body is too slow to withdraw. No wound on boy, no magical beams.", ["T|受けろ。", "T|ぶつけず、外へ。", "N|昼にできた半歩が、", "T|今は、出ない。", "T|間に、合わない。"], "第7話の受けを試すが完全成功させない。"),
        scene("割り込む袖", "panels", "Five successive rescue moments: master's dark green sleeve enters between boy and dart; left forearm intercepts one dart, shallow small blood stain appears on sleeve only; his right hand pushes boy back by shoulder; boy steps safely behind him holding wooden sword; master stands shielding boy, sword still sheathed. Exactly one dart wound on left forearm, restrained non-graphic blood.", ["N|黒い袖が、\n視界を横切った。", "S沈玄|下がれ。", "T|受けたのは、\n俺の剣ではなかった。", "T|左腕。\nあいつの、左腕だ。", "S阿澄|……針が。"], "守る動作の順を明示。負傷はここから継続。"),
        scene("雨の中の仇", "hero", "Tall borderless protective portrait of Shen Xuan standing between boy and rainy corridor, face stern calm, left sleeve with one small dart and restrained blood mark, right hand near sheathed sword hilt. Black feather mantle and wet dark green robe, boy seen only safely behind. No monster or power-up.", ["T|この男は、\n刃なら、避けられた。", "T|なぜ、腕を出した。", "S沈玄|阿澄。目を閉じるな。"], "小さな負傷を一画面で受け止める。"),
        scene("抜かれる音", "panels", "Five final action details: master's right hand grips hilt of single real sword; blade draws only a short distance with rain droplets; two masked attackers in far corridor recoil, faces hidden; boy watches master from behind, gripping wooden sword with two hands; candle on room table still beside bronze emblem. Left forearm wound remains, no killing or severed limbs.", ["N|鞘から、\n金属の音がした。", "T|あの日と、同じ音。", "T|同じ背中。\n今は、その後ろに俺がいる。", "S沈玄|俺から、離れるな。", "N|雨音が、\n一瞬だけ、遠くなった。"], "決着は次回へ。実際の剣戦は短い導入だけ。"),
    ]},
    {"number": 10, "title": "守る手", "change": "師匠は敵を追わず阿澄を守る。止血のため初めてその手に触れ、前世の最期の一言を思い出す。", "scenes": [
        scene("切らない決着", "panels", "Five successive clear non-graphic action moments: master with one real sword completes one precise flat deflection; incoming dart knocked down onto wood; masked attackers retreat into rain at corridor distance, no visible injuries; master does not pursue; master resheathes sword, left sleeve shallow dart wound remains. Boy safely behind with wooden sword.", ["N|剣は、一度だけ動いた。", "T|斬ったのは、人ではない。", "T|飛んでくる針の、\n行き先だけを変えた。", "S阿澄|追わないんですか。", "S沈玄|お前を、一人にはしない。"], "第7話の受けを師匠が実践。追撃や勝利演説なし。"),
        scene("雨のあと", "route", "One continuous vertical aftermath: top rain falling from eaves; middle empty corridor with two harmless darts lying on wood, attackers gone; bottom master's relaxed right hand at his side and left sleeve with a small blood stain, boy approaches from side with a clean folded cloth. White outer paper, rain only within illustration.", ["N|雨だけが、\nいつもの音に戻った。", "T|腕の血は、\n戻らない。", "S阿澄|……袖を、見せてください。"], "戦いの後をすぐ畳まず、血と雨へ視点を下げる。"),
        scene("取れない布", "panels", "Five intimate sequential details: boy holds clean cloth in one hand; his other hand hesitates near wounded dark sleeve; master's uninjured right palm opens briefly; boy stares at palm; boy grips cloth again, decision visible in face. Master left forearm wounded, right hand uninjured, no dart removal graphic detail.", ["S沈玄|浅い。\n心配する傷ではない。", "T|心配だと、\n言っていない。", "T|あの手を、\nまだ、掴めない。", "T|でも、放っておけば、\n血は落ち続ける。", "S阿澄|じっと、していて。"], "第2話の触れられない手を別の選択へ。"),
        scene("巻く手", "panels", "Five consecutive restrained first-aid moments: Ye Qing arrives with clean gauze and holds tray; master has removed the dart offscreen, only small sleeve mark and tiny shallow wound, no gore; boy gently supports master's left forearm through cloth; boy winds clean gauze once while Ye Qing guides; boy ties secure simple knot, master watches. No medical exposition, no magical healing.", ["S葉青|針は抜いた。\nあとは、押さえて。", "T|細い腕で、\n太い腕を支える。", "S葉青|きつすぎないように。", "T|殺すために覚えた手が、\n止めるために動いている。", "N|結び目が、一つできた。"], "手の受け渡しと止血を正確に。傷の処置は非写実的・非説明的。"),
        scene("古い言葉", "panels", "Five emotional sequential shots: boy's hand remains lightly on bandaged left forearm; master's right hand gently covers boy's sleeve cuff for a moment, no gripping; boy's eyes widen at something said; candle reflection on his amber eyes; boy's palm opens, remembering without a new depicted stabbing scene. Bronze seal on nearby table stays hidden from master view.", ["S阿澄|なぜ、俺を庇う。", "N|言ってから、\n声が震えていると気づいた。", "S沈玄|今度こそ、\nお前を死なせない。", "T|今度、こそ？", "T|あの夜も、\n何か、言っていた。"], "シリーズの約束の言葉を、手に触れた瞬間に置く。"),
        scene("聞けなかった声", "hero", "Tall close emotional portrait of boy Asumi, amber eyes shocked and uncertain, left temple bandage, cream robe, a clean gauze band on master's forearm just within lower foreground. Snowy rainy light and candle glow both subtle, white paper. No sword, no enemy, no written text.", ["N|痛みの前に、\n声があった。", "T|『すまない』、ではなく。", "T|……『生きろ』。"], "過去の音の記憶を更新。人物の正体はまだ明かさない。"),
        scene("離さない指", "panels", "Five final quiet choices: boy's fingers loosen from bandaged forearm but do not immediately let go; master notices silently; Ye Qing folds remaining cloth and steps away; bronze emblem half hidden under boy's sleeve on table; boy and master sit in shared silence by window with rain ending, sword sheathed and wooden sword set aside. Master's left forearm now clean white gauze, no further bleeding.", ["S沈玄|……阿澄？", "T|俺を殺した男の手を、\n俺が、支えている。", "T|許したのではない。\n答えが、変わったのでもない。", "S阿澄|その話を、\n今度、ちゃんと聞かせてください。", "N|復讐の前に、\n聞かなければならないことが、\n一つ、できた。"], "第一の区切り。和解・全謎解明を急がず次の章へ。"),
    ]},
]
